### PR TITLE
Added extra case and test, aiming to solve https://github.com/google/…

### PR DESCRIPTION
**Pull request by lbercken**
…closure-compiler/issues/180.

Conditional operator: when the condition and first expression are the
same, OR could be used instead.

Note that this PR is a request to merge this with OUR own development branch. This PR is for internal reviewing only. When we decide we want to PR to Google's repo we can PR from this branch (condition_optimisation_update), so that we can PR per feature update. Hence do **NOT** delete this branch.

### CODE REVIEW

**Comment by r-jsv** [comment]
Looks really good! Let me just test this quickly

**Comment by xmwen** [comment]
Great, we can add a unit test.

**Comment by r-jsv** [comment]
Doesn't work for me. Did you try this @lbercken ?

image

**Comment by r-jsv** [comment]
> Great, we can add a unit test.

He did add one in this file:
test/com/google/javascript/jscomp/PeepholeMinimizeConditionsTest.java

**Comment by r-jsv** [comment]
Is it because I am not setting the run mode to one of the more advance ones? @lbercken

**Comment by lbercken** [comment]
@sveningsonrobin Yes, I did. I wrote a unit test indeed to test this. I think that the optimisation pipeline somehow does another transformation prior to the optimisation I wrote and that in consequence my transformation does not happen, but I guess we can ask the community about this.

I tried different levels of compilation (but peephole optimisation should be part of simple = default), but observed the same you did @sveningsonrobin.

What do you think @sveningsonrobin? Try testing the other cases above to what I added. The unit test shows that the transformation is correct right? I don't know why c = a ? a : b does not get optimised.

**Comment by r-jsv** [comment]
> WHITESPACE_ONLY
> 
> The WHITESPACE_ONLY compilation level removes comments from your code and also removes line breaks, unnecessary spaces, extraneous punctuation (such as parentheses and semicolons), and other whitespace. The output JavaScript is functionally identical to the source JavaScript.
> 
> This compilation level provides the least compression of the three levels.

**Comment by r-jsv** [comment]
Nevermind, the default one is Simple_Optimizations

**Comment by lbercken** [comment]
I'll post this in the [Google group discussion](https://groups.google.com/forum/#!topic/closure-compiler-discuss/M0I-JIoKlXs).

**Comment by r-jsv** [comment]
The problem is that this is the method `performConditionSubstitutions`, which means it only does it on conditions but not for assignments. I don't know if that's the intendent solution, but it's a good start. So let's push it to the main repo and ask them if assignments should be handled as well.

image

**Review by r-jsv — APPROVED** [review]
I think it is a nice solution for the issue. I'm not sure if assignments should be handled as well, but let's start with this for now.

**Comment by lbercken** [comment]
Right! You'd expect that the transformation just happens for each expression with a HOOK (so also in assignments, or whatever). I see that `performConditionSubstitutions` only works on conditions, but I agree with you, it is a good start.

**Review by zhengjian518 — COMMENTED** [review]
Frankly speaking, I haven't completely figure out and test this contribution, just make this review to save time, I'll try to catch up.

**Review by zhengjian518 — APPROVED** [review]

**Pull request merged**
