### PR TITLE
Fixed some minor inconsistencies in the README

### PR DESCRIPTION
**Pull request by r-jsv**

### CODE REVIEW

**Review by lbercken — APPROVED** [review]
Nice.

**Comment by r-jsv** [comment]
Hmm... I start to question this update since you apparently can run the mvn command in Eclipse? Or was that what you did @lbercken ?

**Comment by lbercken** [comment]
Well, this update is only about some punctuation and rephrasing right?

**Comment by r-jsv** [comment]
Yes, but you are running the maven build from inside of Eclipse, and I am not sure if they were in their original readme suggesting to build from inside of eclipse or from command line? It makes a big difference, because then my changes are invalid

**Comment by lbercken** [comment]
The original readme suggests to maven build from the command line yes (so let's stick to that). Hence I still approve this PR.

**Comment by r-jsv** [comment]
Did the base change work? It looks like it, right?

**Comment by lbercken** [comment]
I think it did!

**Comment by r-jsv** [comment]
I will continue and change the other two as well!

**Comment by r-jsv** [comment]
It is safe to merge now, if we want to, right? @lbercken

**Comment by r-jsv** [comment]
I meant we can remove the label haha. But we will still need reviews from the others

**Comment by lbercken** [comment]
Oops, haha ... well they can always review it, so let's wait for that and if something has to be changed, it will have to be outside this pull request then haha, sorry.

**Comment by r-jsv** [comment]
Yes, no problem! I was a bit unclear in my message 👍

**Pull request merged**
